#include "nsISupports.idl"
#include "nsIDOMEvent.idl"

interface nsIDOMBluetoothDevice;

[scriptable, uuid(49294da3-b698-4a7f-aca2-3f9bc44c7625)]
interface nsIDOMBluetoothEvent : nsIDOMEvent
{
  readonly attribute nsIDOMBluetoothDevice device;
};
